services:
  app:
    build: .
    container_name: film-zone
    ports:
      - "60991:5000"
    volumes:
      - sqlite-data:/app/stats-data
    environment:
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0 --port=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite-data:
