services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - EXPLAIN_TEMPLATE_LOADING=True
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000 --debug
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          ignore:
            - stats-data/
            - __pycache__/