# To run this: docker-compose -f docker-compose.yml up -d
services:
  app:
    build: .
    container_name: film-zone
    ports:
      - "60991:5000"
    volumes:
      - sqlite-data:/app/stats-data
    environment:
      - FLASK_ENV=production
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite-data:
